### PR TITLE
Add Example Input Validator to validate if example field exist in plugin.spec | Remove Mitre from AcronymValidator

### PR DESCRIPTION
**Pull request by r7-kszczepanskagorna**
## Description
Add Example Input Validator to validate if example field exist in plugin.spec | Remove Mitre from AcronymValidator

## Testing

There was added unit test.

### CODE REVIEW

**Review by jmcadams-r7 — DISMISSED** [review]

**Review by jschipp-r7 — APPROVED** [review]

**Comment by jschipp-r7** [comment]
@r7-kszczepanskagorna can you get the Unit tests to pass?

Screen Shot 2020-11-24 at 3 22 25 PM

**Comment by r7-kszczepanskagorna** [comment]
@jschipp-r7 
We fixed this error and some other errors and now there is some new error on Github, but not in our local enviroment.
We can't reproduce this error on python version 3.7.3. When we tried do this steps:
```
pip install .
pip install pytest
pytest test_validate_plugin.py
```
and we get this output:

```
============================================================================================================ test session starts ============================================================================================================
platform linux -- Python 3.7.3, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /icon-integrations-validators
collected 27 items

test_validate_plugin.py ...........................                                                                                                                                                                                   [100%]

============================================================================================================= warnings summary ==============================================================================================================
../../usr/local/lib/python3.7/dist-packages/jsonschema/compat.py:6
../../usr/local/lib/python3.7/dist-packages/jsonschema/compat.py:6
  /usr/local/lib/python3.7/dist-packages/jsonschema/compat.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import MutableMapping, Sequence  # noqa

-- Docs: https://docs.pytest.org/en/stable/warnings.html
====================================================================================================== 27 passed, 2 warnings in 25.35s ======================================================================================================
```
We tried also test this on python version 3.8.5 and this test also works correct.
Could you tell us some details about enviroment used on Github so that we can reproduce this error? Is this some Jenkins job? Can we get name of this job?

**Comment by jschipp-r7** [comment]
@mrinehart-r7 how can we get this build to pass so we can release these updates?

**Review by mrinehart-r7 — DISMISSED** [review]

**Comment by mrinehart-r7** [comment]
> @jschipp-r7
> We fixed this error and some other errors and now there is some new error on Github, but not in our local enviroment.
> We can't reproduce this error on python version 3.7.3. When we tried do this steps:
> 
> ```
> pip install .
> pip install pytest
> pytest test_validate_plugin.py
> ```
> 
> and we get this output:
> 
> ```
> ============================================================================================================ test session starts ============================================================================================================
> platform linux -- Python 3.7.3, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
> rootdir: /icon-integrations-validators
> collected 27 items
> 
> test_validate_plugin.py ...........................                                                                                                                                                                                   [100%]
> 
> ============================================================================================================= warnings summary ==============================================================================================================
> ../../usr/local/lib/python3.7/dist-packages/jsonschema/compat.py:6
> ../../usr/local/lib/python3.7/dist-packages/jsonschema/compat.py:6
>   /usr/local/lib/python3.7/dist-packages/jsonschema/compat.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
>     from collections import MutableMapping, Sequence  # noqa
> 
> -- Docs: https://docs.pytest.org/en/stable/warnings.html
> ====================================================================================================== 27 passed, 2 warnings in 25.35s ======================================================================================================
> ```
> 
> We tried also test this on python version 3.8.5 and this test also works correct.
> Could you tell us some details about enviroment used on Github so that we can reproduce this error? Is this some Jenkins job? Can we get name of this job?

It's a GitHub Action - this is the configuration file for it: https://github.com/rapid7/icon-integrations-validators/blob/master/.github/workflows/unit_test.yml

**Review by jschipp-r7 — APPROVED** [review]

**Review by mrinehart-r7 — APPROVED** [review]

**Pull request merged**
